apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-jvm-gradle-build
  annotations:
    description: Executes a JVM build for a Quarkus gradle application
    app.openshift.io/description: Executes a JVM build for a Quarkus gradle application
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    app.openshift.io/vcs-ref: master
  labels:
    version: 0.0.1
spec:
  params:
    - name: git-url
    - name: git-revision
      default: master
    - name: source-dir
      default: /source
    - name: app-name
      default: "dba-next-webhook-app"
    - name: gradle-image
      default: quay.io/ibmgaragecloud/gradle:jdk11
  volumes:
    - name: source
      emptyDir: {}
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(params.source-dir)
    volumeMounts:
      - name: source
        mountPath: $(params.source-dir)
  steps:
    - name: git-clone
      image: quay.io/ibmgaragecloud/alpine-git
      env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-source-credentials
              key: password
              optional: true
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-source-credentials
              key: username
              optional: true
      script: |
        set +x
        if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PASSWORD}" ]]; then
            git clone "$(echo $(params.git-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PASSWORD}@$(echo $(params.git-url) | awk -F '://' '{print $2}')" $(params.source-dir)
        else
            set -x
            git clone $(params.git-url) $(params.source-dir)
        fi
        set -x
        cd $(params.source-dir)
        git checkout $(params.git-revision)
    - name: gradle-quarkus-jvm-build
      image: $(params.gradle-image)
      workingDir: $(params.source-dir)
      script: |
        ./gradlew quarkusBuild --no-daemon
