apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ecm-webhook-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: ecm-webhook-triggerbinding
  template:
    ref: ecm-webhook-triggertemplate
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "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"
