kind: Secret
apiVersion: v1
metadata:
  name: <MY_SECRET_NAME>
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com/MY_GIT_NAMESPACE/MY_APP.git"]
      helper = store
  .git-credentials: |
    https://<MY_USER_NAME>:<MY_GIT_TOKEN>@github.com/<MY_GIT_NAMESPACE>/MY_APP.git